config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :shares
  root to: 'shares#index'
  devise_for :users
  resources :users, only: [:index, :create, :edit, :update, :destroy]
  resource :profile, only: [:show, :edit, :update, :create]
  resources :cars, only: [:new, :create, :destroy]
  resources :parking_places, only: [:create, :destroy, :update]
  resources :parkings
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, inverse_of: :profile, dependent: :destroy
  has_many :cars
  has_many :shares
  has_many :rents
  has_one :parking_place

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true, uniqueness: true
  validates :user_id, presence: true, uniqueness: true

  delegate :email, to: :user

  scope :without_place, -> { where.not(id: ParkingPlace.with_owner.pluck(:profile_id)).includes(:user) }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :force_to_fill_profile!, only: [:edit, :create]
  before_action :set_profile, only: [:show, :edit, :update]

  def show
    authorize! :read, @profile
  end

  def edit
    authorize! :manage, @profile
  end

  def update
    authorize! :update, @profile
    if @profile.update(profile_params)
      redirect_to profile_path, notice: 'Profile was successfully updated.'
    else
      flash[:alert] = @profile.errors.full_messages.join('; ')
      render :edit
    end
  end

  def create
    @profile = current_user.build_profile(profile_params)
    authorize! :create, @profile
    if @profile.save
      redirect_to profile_path, notice: 'Profile was successfully created.'
    else
      flash[:alert] = @profile.errors.full_messages.join('; ')
      render :edit
    end
  end

  private

  def set_profile
    @profile = current_user.profile || current_user.build_profile
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :phone_number, :user_id)
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
  def full_name(resource)
    if resource.first_name && resource.last_name
      [resource.first_name, resource.last_name].join(' ')
    else
      resource.email
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def full_name(resource)
    if resource.first_name && resource.last_name
      [resource.first_name, resource.last_name].join(' ')
    else
      resource.email
    end
  end
end

app/views/profiles/_form.html.haml
= form_for @profile, url: profile_path do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control'
  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control'
  .form-group
    = f.label :phone_number
    = f.text_field :phone_number, class: 'form-control'
  = f.submit 'Save', class: 'btn btn-primary'

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

app/views/profiles/show.html.haml
.row
  .col-sm
    .card
      .card-body
        %h4.card-title= full_name(@profile)
        %h6.card-subtitle.mb-2.text-muted= @profile.phone_number
        %p.card-text= @profile.email
  .col-md
    .card
      .card-body
        %h4.card-title Your cars
        -if @profile.cars.any?
          = render 'cars/list', cars: @profile.cars
        - else
          %h6.card-subtitle.mb-2.text-muted You don't have any cars yet.
    %br
    .text-right
      - if can? :create, Car
        = link_to new_car_path, class: 'btn btn-float btn-primary waves-attach waves-circle' do
          %i.material-icons add

%hr
.row
  .col-sm
    .card
      .card-body
        %h4.card-title Your shares
        - if @profile.shares.any?
          = render 'shares/list', shares: @profile.shares
        - else
          %h6.card-subtitle.mb-2.text-muted You don't have any shares yet
    %br
      .text-right
        - if can? :create, Share
          = link_to new_share_path, class: 'btn btn-float btn-primary waves-attach waves-circle' do
            %i.material-icons add
  .col-sm
    .card
      .card-body
        %h4.card-title Your rents
        - if @profile.rents.any?
          = render 'rents/list', rents: @profile.rents
        - else
          %h6.card-subtitle.mb-2.text-muted You don't have any rents yet


= link_to 'Edit', edit_profile_path
\|
= link_to 'Back', root_path