config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :shares
  root to: 'shares#index'
  devise_for :users
  resources :users, only: [:index, :create, :edit, :update, :destroy]
  resource :profile, only: [:show, :edit, :update, :create]
  resources :cars, only: [:new, :create, :destroy]
  resources :parking_places, only: [:create, :destroy, :update]
  resources :parkings
end

app/models/parking.rb
class Parking < ApplicationRecord
  has_many :parking_places

  validates :name, presence: true, uniqueness: true
  validates :rank, presence: true, numericality: { only_integer: true }
  validates :order, presence: true, inclusion: { in: %w(asc desc) }, allow_nil: false
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_parking, only: [:show, :edit, :update, :destroy]

  def index
    @parkings = Parking.all
    authorize! :read, @parkings
  end

  def show
    authorize! :read, @parking
  end

  def new
    @parking = Parking.new
    authorize! :create, @parking
  end

  def edit
    authorize! :edit, @parking
  end

  def create
    @parking = Parking.new(parking_params)
    authorize! :create, @parking
    if @parking.save
      redirect_to parkings_url, notice: 'Parking was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize! :update, @parking
    if @parking.update(parking_params)
      redirect_to parkings_url, notice: 'Parking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @parking
    @parking.destroy
    redirect_to parkings_url, notice: 'Parking was successfully destroyed.'
  end

  private
    def set_parking
      @parking = Parking.find(params[:id])
    end

    def parking_params
      params.require(:parking).permit(:name, :rank, :order)
    end
end

app/views/parkings/_form.html.haml
- if @parking.errors.any?
  #error_explanation
    %h2= "#{pluralize(@parking.errors.count, "error")} prohibited this parking from being saved:"
    %ul
      - @parking.errors.full_messages.each do |message|
        %li= message

= form_for @parking, html: {class: 'form-inline'} do |f|
  = f.label :name, class: 'mr-sm-2'
  = f.text_field :name, class: 'form-control mb-2 mr-sm-2 mb-sm-0', placeholder: 'Подземная парковка'

  = f.label :rank, class: 'mr-sm-2'
  = f.number_field :rank, class: 'form-control mb-2 mr-sm-2 mb-sm-0'

  = f.label :order, class: 'mr-sm-2'
  = f.select :order, ['asc', 'desc'], {}, { class: 'form-control mb-2 mr-sm-2 mb-sm-0' }
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/parkings/edit.html.haml
%h1 Editing parking

= render 'form'
%br
= link_to 'Show', @parking
\|
= link_to 'Back', parkings_path

app/views/parkings/index.html.haml
%h2 Parkings

.card
  .card-body
    %table.table.table-striped.table-bordered.table-hover
      %thead.thead-dark
        %tr
          %th Name
          %th Rank
          %th Order
          %th Show
          -if can? :manage, :parkings
            %th
            %th

      %tbody
        - @parkings.each do |parking|
          %tr
            %td= parking.name
            %td= parking.rank
            %td= parking.order
            %td= link_to 'Show', parking
            -if can? :manage, :parkings
              %td= link_to 'Edit', edit_parking_path(parking)
              %td= link_to 'Destroy', parking, method: :delete, data: { confirm: 'Are you sure?' }

%br
-if can? :create, :parkings
  .text-right
    = link_to new_parking_path, class: 'btn btn-float btn-primary waves-attach waves-circle' do
      %i.material-icons add

app/views/parkings/new.html.haml
%h1 New parking

= render 'form'

%br
= link_to 'Back', parkings_path

app/views/parkings/show.html.haml
- if can? :create, :parking_place
  .card
    .card-body
      = render 'parking_places/form', parking_place: ParkingPlace.new
%h2= @parking.name
%ul.list-group
  - @parking.parking_places.each do |place|
    %li.list-group-item
      -if can? :manage, :parking_places
        = render 'parking_places/form', parking_place: place
      -else
        = place.number

%br
= link_to 'Back', parkings_path