config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :shares
  root to: 'shares#index'
  devise_for :users
  resources :users, only: [:index, :create, :edit, :update, :destroy]
  resource :profile, only: [:show, :edit, :update, :create]
  resources :cars, only: [:new, :create, :destroy]
  resources :parking_places, only: [:create, :destroy, :update]
  resources :parkings
end

app/views/layouts/_complete_profile.html.haml
.alert.alert-primary{'role'=>"alert"}
  =link_to 'Edit profile', edit_profile_path

app/views/layouts/_navbar.html.haml
%nav.navbar.justify-content-between{:style => "background-color: #38b349; color: white"}
  = link_to 'Lohika', root_path, class: 'navbar-brand'
  - if user_signed_in?
    %ul.navbar-nav
      -if can? :read, :users
        %li.nav-item
          = link_to 'Users', users_path, class: 'nav-link'
      -if can? :read, :parkings
        %li.nav-item
          = link_to 'Parkings', parkings_path, class: 'nav-link'
      %li.nav-item
        - if with_full_profile?
          = link_to "Profile(#{current_user.email})", profile_path, class: 'nav-link'
        - else
          = link_to edit_profile_path, class: 'nav-link' do
            %span
              = "Profile(#{current_user.email})"
              %span.badge.badge-secondary
                !
      %li.nav-item
        = link_to 'Sign out', destroy_user_session_path, class: 'nav-link'
  - else
    %ul.navbar-nav
      %li.nav-item
        = link_to 'Sign in', new_user_session_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LohikaParking
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .container
      - if user_signed_in? && !with_full_profile?
        = render 'layouts/complete_profile'
      - if notice
        %p.alert= notice
      - if alert
        %p.alert= alert
      %br
      = yield